# Generated by Django 4.2.1 on 2023-10-19 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AhorroVista',
        ),
        migrations.DeleteModel(
            name='CaptacionAhorroVista',
        ),
        migrations.DeleteModel(
            name='Cdats',
        ),
        migrations.DeleteModel(
            name='Colocaciones',
        ),
        migrations.DeleteModel(
            name='Cooviahorro',
        ),
        migrations.DeleteModel(
            name='CrecimeintoBaseSocial',
        ),
        migrations.DeleteModel(
            name='CrecimientoCartera',
        ),
        migrations.DeleteModel(
            name='CrecimientoCdats',
        ),
        migrations.DeleteModel(
            name='CrecimientoCooviahorro',
        ),
        migrations.DeleteModel(
            name='Utilidad',
        ),
    ]
