# Generated by Django 4.2.6 on 2023-10-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colocaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasaMin', models.CharField(max_length=50)),
                ('tasaMax', models.CharField(max_length=50)),
                ('since', models.CharField(max_length=50)),
                ('until', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
