# Generated by Django 4.2.1 on 2023-10-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rangoMin', models.CharField(max_length=50)),
                ('rangoMax', models.CharField(max_length=50)),
                ('oficina', models.CharField(max_length=50)),
            ],
        ),
    ]
