# Generated by Django 4.2.1 on 2023-10-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilidad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilidad',
            name='oficina',
        ),
        migrations.AddField(
            model_name='utilidad',
            name='big',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='utilidad',
            name='medium',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='utilidad',
            name='small',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
