# Generated by Django 4.2.1 on 2023-10-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AhorroVista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.CharField(max_length=50)),
                ('until', models.CharField(max_length=50)),
                ('porcentaje', models.CharField(max_length=50)),
            ],
        ),
    ]
